_wandb:
    value:
        cli_version: 0.24.0
        e:
            x6687s10habtkq3jgtt2dbvpztelzd12:
                args:
                    - exp_config=ez/config/exp/pong.yaml
                codePath: ez/train.py
                codePathLocal: ez/train.py
                cpu_count: 104
                cpu_count_logical: 208
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "27705920589824"
                        used: "48735342592"
                email: connorbrown059@gmail.com
                executable: /home/ubuntu/miniconda3/envs/ezv2/bin/python
                git:
                    commit: 2e3b53b84d26bba216ecd5c20c8022b4ad93f0c9
                    remote: https://github.com/cbrownaz24/EfficientZero-v2.git
                gpu: NVIDIA H100 80GB HBM3
                gpu_count: 8
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-38c67d95-4bd7-0910-f1c4-58f789615c9c
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-e28cc4be-2c24-a0da-6be1-4a725557ee2d
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-0b8e0be9-ff20-8725-9a3e-95905b5d9e76
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-5d147777-cd7c-c2fc-42fa-e619bb363ddf
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-7ebd83b8-d0ec-6ae1-7ee7-4d1d5b0cfaaf
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-29c34df4-0444-6048-c8bd-bc87e5e5af25
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-541e6491-cfd5-cc9e-006f-ea3fdb2e6aec
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "85520809984"
                      name: NVIDIA H100 80GB HBM3
                      uuid: GPU-b13bebf4-7ca7-e089-8a60-04d159812e1f
                host: 209-20-158-25
                memory:
                    total: "1902346055680"
                os: Linux-5.15.0-143-generic-x86_64-with-glibc2.17
                program: ez/train.py
                python: CPython 3.8.20
                root: /lambda/nfs/ezv2/EfficientZero-v2
                startedAt: "2026-01-21T04:02:40.017955Z"
                writerId: x6687s10habtkq3jgtt2dbvpztelzd12
        m: []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 30
                - 41
                - 50
                - 79
                - 105
            "2":
                - 1
                - 30
                - 41
                - 50
                - 79
                - 105
            "3":
                - 13
            "4": 3.8.20
            "5": 0.24.0
            "12": 0.24.0
            "13": linux-x86_64
